kind: pipeline
name: build
steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: test/test
      context: ./server/
      dockerfile: ./server/Dockerfile
      tags:
        - latest
      dry_run: true
