---
kind: pipeline
name: build api
steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: dockerhub.mlunax.com/lunax/shrtner-api
      context: ./server/
      dockerfile: ./server/Dockerfile
      registry: dockerhub.mlunax.com
      cache_from:
        - dockerhub.mlunax.com/lunax/shrtner-api:latest
      tags:
        - latest
      dry_run: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      target:
        exclude:
          - production
  - name: docker-push
    image: plugins/docker
    settings:
      repo: dockerhub.mlunax.com/lunax/shrtner-api
      context: ./server/
      dockerfile: ./server/Dockerfile
      registry: dockerhub.mlunax.com
      cache_from:
        - dockerhub.mlunax.com/lunax/shrtner-api:latest
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - promote
      target:
        - production

trigger:
  ref:
    - refs/heads/master
    - refs/tags/*
---
kind: signature
hmac: 21b924f3620ddec53ca4c9abd0882d1a926472433132122838292c555d2b8dbd
