version: "3.3"

volumes:
  db:

services:
  redis:
    image: redis:alpine
    volumes:
      - db:/data
      - ./redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    ports: [6379:6379]

  shrtner:
    ports: [5000:5000]
    build: ./server
    env_file:
      - ./.env
